title: Vanity ETH
description: Vanity-ETH is a browser-based tool to generate Ethereum vanity addresses. Use the power of your browser to generate a custom ETH vanity address!
url: vanity-eth.tk
logo: https://i.imgur.com/lv6Gej5.png
google_site_verification: DFWJVWz9IRrh-wjBxn0Y8ith5FTqMeJTSUtuJ595BEs

plugins:
  - jekyll-seo-tag
